name: Bug Report
description: Report a bug to help us improve Ivy Framework
labels: ["bug"]
type: bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of the problem
      placeholder: Describe what went wrong...
