using System.ComponentModel.DataAnnotations;

namespace Ivy.Test;

public class TestModel
{
    [Required]
    public string RequiredString { get; set; } = string.Empty;

    public string? NullableString { get; set; }

    public string NonNullableString { get; set; } = string.Empty;

    public decimal Decimal { get; set; } = 1;
}

public class DisplayAttributeTestModel
{
    [Display(Name = "Where are you based?")]
    public int CountryId { get; set; }

    [Display(Name = "User ID")]
    public int UserId { get; set; }

    [Display(Name = "Government ID")]
    public int GovId { get; set; }

    [Display(Name = "Id")]
    public int Id { get; set; }

    public int AutoGeneratedCountryId { get; set; }

    public int AutoGeneratedUserId { get; set; }

    public int GovIdAuto { get; set; }

    public int PlainId { get; set; }
}

public class FormHelpersTest
{
    [Fact]
    public void IsRequired_ShouldReturnTrue_WhenRequiredAttributeIsPresentOnProperty()
    {
        // Arrange
        var propertyInfo = typeof(TestModel).GetProperty(nameof(TestModel.RequiredString));

        // Act
        var result = FormHelpers.IsRequired(propertyInfo!);

        // Assert
        Assert.True(result);
    }

    [Fact]
    public void IsRequired_ShouldReturnFalse_WhenPropertyIsNullableString()
    {
        // Arrange
        var propertyInfo = typeof(TestModel).GetProperty(nameof(TestModel.NullableString));

        // Act
        var result = FormHelpers.IsRequired(propertyInfo!);

        // Assert
        Assert.False(result);
    }

    [Fact]
    public void IsRequired_ShouldReturnTrue_WhenPropertyIsNonNullableStringWithoutRequiredAttribute()
    {
        // Arrange
        var propertyInfo = typeof(TestModel).GetProperty(nameof(TestModel.NonNullableString));

        // Act
        var result = FormHelpers.IsRequired(propertyInfo!);

        // Assert
        Assert.True(result);
    }

    [Fact]
    public void IsRequired_ShouldReturnFalse_WhenPropertyIsNotString()
    {
        // Arrange
        var propertyInfo = typeof(TestModel).GetProperty(nameof(TestModel.Decimal));

        // Act
        var result = FormHelpers.IsRequired(propertyInfo!);

        // Assert
        Assert.False(result);
    }
}

public class ValidationTestModel
{
    [AllowedValues("A", "B", "C")]
    public string[] Tags { get; set; } = Array.Empty<string>();
}

public class ValidationTest
{
    [Fact]
    public void GetValidators_ShouldPass_WhenCollectionContainsAllowedValues()
    {
        // Arrange
        var propertyInfo = typeof(ValidationTestModel).GetProperty(nameof(ValidationTestModel.Tags));
        var validators = FormHelpers.GetValidators(propertyInfo!);
        var validValue = new[] { "A", "B" };

        // Act
        var isValid = true;
        foreach (var validator in validators)
        {
            var (valid, _) = validator(validValue);
            if (!valid)
            {
                isValid = false;
                break;
            }
        }

        // Assert
        Assert.True(isValid, "Validation should pass for allowed values in collection");
    }

    [Fact]
    public void GetValidators_ShouldFail_WhenCollectionContainsDisallowedValue()
    {
        // Arrange
        var propertyInfo = typeof(ValidationTestModel).GetProperty(nameof(ValidationTestModel.Tags));
        var validators = FormHelpers.GetValidators(propertyInfo!);
        var invalidValue = new[] { "A", "D" }; // "D" is not allowed

        // Act
        var isValid = true;
        foreach (var validator in validators)
        {
            var (valid, _) = validator(invalidValue);
            if (!valid)
            {
                isValid = false;
                break;
            }
        }

        // Assert
        Assert.False(isValid, "Validation should fail when collection contains disallowed values");
    }
}

public class AllowedValuesTestModel
{
    [AllowedValues("USA", "Canada", "UK")]
    public string Country { get; set; } = "USA";

    [AllowedValues("Tech", "Sports", "Music")]
    public string[] Interests { get; set; } = [];

    public string NoAttribute { get; set; } = "";
}

public class AllowedValuesTest
{
    [Fact]
    public void GetAllowedValues_ShouldReturnValues_WhenAttributeIsPresent()
    {
        var propertyInfo = typeof(AllowedValuesTestModel).GetProperty(nameof(AllowedValuesTestModel.Country));
        var values = FormHelpers.GetAllowedValues(propertyInfo!);
        Assert.NotNull(values);
        Assert.Equal(new object[] { "USA", "Canada", "UK" }, values);
    }

    [Fact]
    public void GetAllowedValues_ShouldReturnNull_WhenNoAttribute()
    {
        var propertyInfo = typeof(AllowedValuesTestModel).GetProperty(nameof(AllowedValuesTestModel.NoAttribute));
        var values = FormHelpers.GetAllowedValues(propertyInfo!);
        Assert.Null(values);
    }

    [Fact]
    public void ScaffoldFields_ShouldCreateSelectFactory_WhenStringHasAllowedValues()
    {
        var fields = FormScaffolder.ScaffoldFields<AllowedValuesTestModel>(typeof(AllowedValuesTestModel));
        Assert.NotNull(fields["Country"].InputFactory);
    }

    [Fact]
    public void ScaffoldFields_ShouldCreateSelectFactory_WhenStringArrayHasAllowedValues()
    {
        var fields = FormScaffolder.ScaffoldFields<AllowedValuesTestModel>(typeof(AllowedValuesTestModel));
        Assert.NotNull(fields["Interests"].InputFactory);
    }
}

public class FormScaffolderTest
{
    [Fact]
    public void ScaffoldFields_ShouldNotTruncateDisplayAttributeName_WhenFieldNameEndsWithId()
    {
        // Arrange
        var modelType = typeof(DisplayAttributeTestModel);

        // Act
        var fields = FormScaffolder.ScaffoldFields<DisplayAttributeTestModel>(modelType);

        // Assert
        Assert.Equal("Where are you based?", fields["CountryId"].Label);
        Assert.Equal("User ID", fields["UserId"].Label);
        Assert.Equal("Government ID", fields["GovId"].Label);
        Assert.Equal("Id", fields["Id"].Label);
    }

    [Fact]
    public void ScaffoldFields_ShouldTrimIdSuffix_FromAutoGeneratedLabels()
    {
        // Arrange
        var modelType = typeof(DisplayAttributeTestModel);

        // Act
        var fields = FormScaffolder.ScaffoldFields<DisplayAttributeTestModel>(modelType);

        // Assert
        Assert.Equal("Auto Generated Country", fields["AutoGeneratedCountryId"].Label);
        Assert.Equal("Auto Generated User", fields["AutoGeneratedUserId"].Label);
    }

    [Fact]
    public void ScaffoldFields_ShouldNotTrimIdSuffix_FromGovIdOrPlainId()
    {
        // Arrange
        var modelType = typeof(DisplayAttributeTestModel);

        // Act
        var fields = FormScaffolder.ScaffoldFields<DisplayAttributeTestModel>(modelType);

        // Assert
        // GovIdAuto should not be trimmed because it doesn't end with "Id" (it ends with "Auto")
        Assert.Equal("Gov Id Auto", fields["GovIdAuto"].Label);
        // PlainId should be trimmed to "Plain" (not "Id" or "GovId")
        Assert.Equal("Plain", fields["PlainId"].Label);
    }
}
